server:
  port: 8080

#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    generate-unique-name: true
#    schema:
#      - classpath:schema.sql
#      - classpath:test.sql
#    initialization-mode: always

########################
# mybatis setting
########################
mybatis:
  mapper-locations: sql-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

########################
#
########################
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      cache:
        time-to-live: 1s

########################
# data source setting
########################
spring:
  db1:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${datasources1.url}?/serverTimezone=UTC&characterEncoding=UTF-8
      username: ${datasources1.user}
      password: ${datasources1.password}

  db2:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://${datasources2.url}?/serverTimezone=UTC&characterEncoding=UTF-8
      username: ${datasources2.user}
      password: ${datasources2.password}
########################
# logging setting
########################
#logging:
#  level: debug

